include:
  - project: 'orderlynetwork/orderly-devops/orderly-common/common-ci'
    ref: main
    file: '/common-orderly-network-dev.yaml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  SERVICE_NAME: storybook
  IMAGE_NAME: storybook
